FROM alpine:latest
#Instalado de paquetes
RUN apk update && apk add vim git curl net-tools sudo zsh unzip nano  nmap iputils-ping
#RUN apk add --no-cache lxde-common lxdm dbus-x11 xf86-video-vesa xorg-server xfce4-terminal
#RUN apk add tigervnc lxqt-desktop lximage

RUN apk update && apk add --no-cache \
  openbox \
  tigervnc \
  xterm \
  dbus \
  xauth \
  ttf-dejavu \
  bash \
  sudo
