services:
  srv_debian:
    build:
      context: ./debian
      dockerfile: Dockerfile
    image: img_debian:latest
    container_name: srv_debian
    hostname: srv_debian
    networks:
      net_30:
        ipv4_address: 30.0.0.34
    ports:
      - "5901:5901"
      - "2201:22"
    tty: true

#  srv_fedora:
#    image: jrei/systemd-fedora
#    container_name: srv_fedora
#    hostname: srv_fedora
#    privileged: true
#    cgroupns: host
#    ports:
#      - "5902:5901"
#      - "2202:22"
#    networks:
#      net_30:
#        ipv4_address: 30.0.0.35
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:rw
#    tmpfs:
#      - /run
#      - /run/lock
#    command: /sbin/init

  srv_ubuntu:
    build:
      context: ./ubuntu
      dockerfile: Dockerfile
    image: img_ubuntu:latest
    container_name: srv_ubuntu
    hostname: srv_ubuntu
    networks:
      net_30:
        ipv4_address: 30.0.0.36
    ports:
      - "5903:5901"
      - "2203:22"
    tty: true

  srv_almalinux:
    build:
      context: ./almalinux
      dockerfile: Dockerfile
    image: img_almalinux:latest
    container_name: srv_almalinux
    privileged: true
    hostname: srv_almalinux
    networks:
      net_40:
        ipv4_address: 40.0.0.37
    ports:
      - "5904:5901"
      - "2204:22"
      - "7070:7070"
    tty: true

  srv_alpine:
    build:
      context: ./alpine
      dockerfile: Dockerfile
    image: img_alpine:latest
    container_name: srv_alpine
    hostname: srv_alpine
    networks:
      net_40:
        ipv4_address: 40.0.0.38
    ports:
      - "5905:5901"
      - "2205:22"
    tty: true

  srv_rockylinux:
    build:
      context: ./rockylinux
      dockerfile: Dockerfile
    image: img_rockylinux9.3:latest
    container_name: srv_rockylinux
    hostname: srv_rockylinux
    networks:
      net_40:
        ipv4_address: 40.0.0.39
    ports:
      - "5906:5901"
      - "2206:22"
    tty: true


networks:
  net_30:
    external: true
  net_40:
    external: true
