#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export XDG_SESSION_TYPE=x11
export GDK_BACKEND=x11
export LIBGL_ALWAYS_SOFTWARE=1
export MUTTER_DEBUG_ENABLE_NOEGL=1
export MUTTER_DEBUG_DISABLE_HW_CURSORS=1
export DISPLAY=:1
eval $(dbus-launch --sh-syntax --exit-with-session)
gnome-session --debug
